import {
  FINCRA_API_KEY,
  FINCRA_API_URL,
  PRESTO_API,
  SENTRY_DSN,
  NATIVE_NOTIFY_TOKEN,
  NATIVE_NOTIFY_ID,
} from "@env";

export default {
  FINCRA_API_KEY,
  FINCRA_API_URL,
  PRESTO_API,
  SENTRY_DSN,
  NATIVE_NOTIFY_TOKEN,
  NATIVE_NOTIFY_ID,
};
